// Code generated by sqlc. DO NOT EDIT.
// source: admin.sql

package db

import (
	"context"
)

const truncateAll = `-- name: TruncateAll :exec
TRUNCATE
    benchmarks,
    changes,
    changes_ranked,
    commit_positions,
    commit_refs,
    commits,
    datafiles,
    modules,
    packages,
    points,
    properties,
    results,
    tasks
`

func (q *Queries) TruncateAll(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateAllStmt, truncateAll)
	return err
}
