// Code generated by sqlc. DO NOT EDIT.
// source: admin.sql

package db

import (
	"context"
)

const truncateNonStatic = `-- name: TruncateNonStatic :exec
TRUNCATE
    benchmarks,
    datafiles,
    packages,
    properties,
    results,
    tasks
`

// TruncateNonStatic is a destructive query that deletes everything apart from
// commits and modules.
func (q *Queries) TruncateNonStatic(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateNonStaticStmt, truncateNonStatic)
	return err
}
