// Code generated by sqlc. DO NOT EDIT.
// source: commits.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const commit = `-- name: Commit :one
SELECT sha, tree, parents, author_name, author_email, author_time, committer_name, committer_email, commit_time, message FROM commits
WHERE sha = $1 LIMIT 1
`

func (q *Queries) Commit(ctx context.Context, sha []byte) (Commit, error) {
	row := q.db.QueryRowContext(ctx, commit, sha)
	var i Commit
	err := row.Scan(
		&i.SHA,
		&i.Tree,
		pq.Array(&i.Parents),
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorTime,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitTime,
		&i.Message,
	)
	return i, err
}
