// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Benchmark struct {
	UUID        uuid.UUID
	PackageUUID uuid.UUID
	FullName    string
	Name        string
	Unit        string
	Parameters  json.RawMessage
}

type Commit struct {
	SHA            []byte
	Tree           []byte
	Parents        [][]byte
	AuthorName     sql.NullString
	AuthorEmail    sql.NullString
	AuthorTime     sql.NullTime
	CommitterName  sql.NullString
	CommitterEmail sql.NullString
	CommitTime     sql.NullTime
	Message        sql.NullString
}

type Datafile struct {
	UUID   uuid.UUID
	Name   string
	SHA256 []byte
}

type Module struct {
	UUID    uuid.UUID
	Path    string
	Version sql.NullString
}

type Package struct {
	UUID         uuid.UUID
	ModuleUUID   uuid.UUID
	RelativePath string
}

type Property struct {
	UUID   uuid.UUID
	Fields json.RawMessage
}

type Result struct {
	UUID            uuid.UUID
	DatafileUUID    uuid.UUID
	Line            int32
	BenchmarkUUID   uuid.UUID
	CommitSHA       []byte
	EnvironmentUUID uuid.UUID
	MetadataUUID    uuid.UUID
	Iterations      sql.NullInt64
	Value           float64
}
