// Code generated by make_assets.go. DO NOT EDIT.

package main

var Assets = map[string][]byte{
	"templates/mods.html": []byte("<!DOCTYPE html>\n<html>\n  <head>\n    <title>Modules</title>\n  </head>\n  <body>\n    <ul>\n      {{ range .Modules }}\n      <li>{{ .Path }} <small>{{ .Version }}</small></li>\n      {{ end }}\n    </ul>\n  </body>\n</html>\n"),
}
