// Code generated by make_assets.go. DO NOT EDIT.

package main

var Assets = map[string][]byte{
	"templates/mods.html": []byte("<!DOCTYPE html>\n<html>\n  <head>\n    <title>Modules</title>\n  </head>\n  <body>\n    Hello, World!\n  </body>\n</html>\n"),
}
