// Code generated by "enumer -type TaskStatus -output taskstatus_enum.go -trimprefix TaskStatus -transform snake"; DO NOT EDIT.

//
package entity

import (
	"fmt"
)

const _TaskStatusName = "createdin_progressresult_upload_startedresult_uploadedcomplete_successcomplete_errorhaltedstale_timeout"

var _TaskStatusIndex = [...]uint8{0, 7, 18, 39, 54, 70, 84, 90, 103}

func (i TaskStatus) String() string {
	i -= 1
	if i >= TaskStatus(len(_TaskStatusIndex)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i+1)
	}
	return _TaskStatusName[_TaskStatusIndex[i]:_TaskStatusIndex[i+1]]
}

var _TaskStatusValues = []TaskStatus{1, 2, 3, 4, 5, 6, 7, 8}

var _TaskStatusNameToValueMap = map[string]TaskStatus{
	_TaskStatusName[0:7]:    1,
	_TaskStatusName[7:18]:   2,
	_TaskStatusName[18:39]:  3,
	_TaskStatusName[39:54]:  4,
	_TaskStatusName[54:70]:  5,
	_TaskStatusName[70:84]:  6,
	_TaskStatusName[84:90]:  7,
	_TaskStatusName[90:103]: 8,
}

// TaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskStatusString(s string) (TaskStatus, error) {
	if val, ok := _TaskStatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskStatus values", s)
}

// TaskStatusValues returns all values of the enum
func TaskStatusValues() []TaskStatus {
	return _TaskStatusValues
}

// IsATaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskStatus) IsATaskStatus() bool {
	for _, v := range _TaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
